version: '3'

services:
  hygeo:
    build: .
    container_name: hygeo
    user: root
    ports:
      - "8888:8888"
    volumes:
      - ./:/jupyter
    command: >
      start.sh jupyter lab --LabApp.token='' --ContentsManager.root_dir='/jupyter' --NotebookApp.notebook_dir='/jupyter' --NotebookApp.contents_manager_class='ipymd.IPymdContentsManager' --NotebookApp.contents_manager_class='jupytext.TextFileContentsManager'
